### ISSUE TITLE
Error: Task cannot start with the word "start"

### ISSUE THREAD

**Issue by krzyklo** [farseer90718/vim-taskwarrior#153]
When my task list in Vim is started with the word "start" I get following error. 
I do not get error when I use capital "Start".

Task list:
== Plan wk3-4 || project:ssdsd==
* [ ] recipe sdfds sddd for coatsdsdfsdfsdsdfsdsdf sdfsdfsfdfor
* [ ] start sth

Error:
`Error detected while processing BufWrite Auto commands for "*.wiki":
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kk/.vim/plugged/taskwiki/taskwiki/errors.py", line 26, in wrapped_function
    original_function(*args, **kwargs)
  File "/home/kk/.vim/plugged/taskwiki/taskwiki/decorators.py", line 10, in wrapped_function
    original_function(*args, **kwargs)
  File "/home/kk/.vim/plugged/taskwiki/taskwiki/main.py", line 60, in update_to_tw
    c.save_tasks()
  File "/home/kk/.vim/plugged/taskwiki/taskwiki/cache.py", line 206, in save_tasks
    task.save_to_tw()
  File "/home/kk/.vim/plugged/taskwiki/taskwiki/vwtask.py", line 267, in save_to_tw
    self.task.save()
  File "/usr/local/lib/python3.6/dist-packages/tasklib/task.py", line 415, in save
    self.backend.save_task(self)
  File "/usr/local/lib/python3.6/dist-packages/tasklib/backends.py", line 346, in save_task
    output = self.execute_command(args)
  File "/usr/local/lib/python3.6/dist-packages/tasklib/backends.py", line 297, in execute_command
    raise TaskWarriorException(error_msg)
tasklib.backends.TaskWarriorException: TASKRC override: /home/kk/.taskrc
Configuration override rc.confirmation:no
Configuration override rc.dependency.confirmation:no
Configuration override rc.recurrence.confirmation:no
Configuration override rc.json.array:off
Configuration override rc.bulk:0
Configuration override rc.context:
The expression could not be evaluated.`

**Comment by krzyklo** [comment]
I am not sure whether it is vimwiki error or vim-taskwarrior?
